version: '3.8'

services:
  backend:
    build: ./recipe_app
    volumes:
      - ./recipe_app:/app
    ports:
      - "8000:8000"
    env_file:
      - ./recipe_app/.env
    depends_on:
      - db

  frontend:
    build: ./recipe-frontend
    volumes:
      - ./recipe-frontend:/app
    ports:
      - "8080:8080"
    env_file:
      - ./recipe-frontend/.env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
