version: '3.8'

services:
  backend:
    build: ./recipe_app
    volumes:
      - ./recipe_app:/app
    ports:
      - "8000:8000"
    env_file:
      - ./recipe_app/.env

  frontend:
    build: ./recipe-frontend
    volumes:
      - ./recipe-frontend:/app
    ports:
      - "8080:8080"
    env_file:
      - ./recipe-frontend/.env.local
    command: npm run serve


volumes:
  postgres_data:
