# Generated by Django 4.2.13 on 2024-05-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_ingredient_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='photo',
        ),
    ]
